db.t_delivery_order.aggregate([
{$match:{_id:{$in:[
"DO202500019552",
"DO202500019560",
"DO202500020681",
"DO202500021288",
"DO202500020084",

]}}},
{$unwind:"$detail"},
{$group:{
_id:{
noDO:"$_id",
unitName:"$unitName",
status:"$detail.status",
status:"$detail.status",
skuName:"$detail.skuName",
tanggalDiterima:"$detail.tanggalDiterima",
tanggalDiterima:"$detail.tanggalDiterima",
receiveByName:"$detail.receiveByName",
receiveById:"$detail.receiveById",
}
}},
{$project:{
_id:0,
noDO:"$_id.noDO",
unitName:"$_id.unitName",
status:"$_id.status",
status:"$_id.status",
skuName:"$_id.skuName",
tanggalDiterima:"$_id.tanggalDiterima",
tanggalDiterima:"$_id.tanggalDiterima",
receiveByName:"$_id.receiveByName",
receiveById:"$_id.receiveById",
}}
])